[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "cloudisk"
version = "0.1.0"
description = "A decentralized content distribution system. Run your own cloud."
readme = "README.md"
license = { text = "" }
requires-python = ">=3.11"
scripts.cloudisk = "cloudisk:main"
dependencies = [
    "fastapi>=0.121.0",
    "filetype>=1.2.0",
    "httpx>=0.28.1",
    "python-multipart>=0.0.20",
    "sqlmodel>=0.0.27",
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.4.0",
    "ruff>=0.14.3",
]

test = [
    "coverage>=7.11.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

[tool.coverage.run]
branch = true
omit = [
    "__init__.py",
    "__main__.py",
    "static/*",
    "tests/*",
    "cloudisk/cli/*",
]

[tool.coverage.report]
precision = 2
show_missing = true
fail_under = 90

[tool.ruff]
line-length = 90
target-version = "py311"

[tool.ruff.lint]
extend-select = ["C", "D", "E", "F", "I", "N", "T", "W"]
exclude = [
    "venv",
    "env",
    ".venv",
    ".env",
    "__init__.py",
]
select = ["C", "D", "E", "F", "I", "N", "T", "W"]
ignore = ["D100", "D101", "D102", "D103", "D203", "D205","D212", "D413", "N802"]

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
