[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "cloudisk"
version = "0.1.0"
description = "Uncentralized content distribution system, on your own cloud"
readme = "README.md"
license = { text = "" }
requires-python = ">=3.11"
scripts.cloudisk = "cloudisk:main"
dependencies = [
    "fastapi>=0.121.0",
    "filetype>=1.2.0",
    "sqlmodel>=0.0.27",
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.4.0",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.3",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

[tool.ruff]
line-length = 90
target-version = "py311"

[tool.ruff.lint]
extend-select = ["C", "D", "E", "F", "I", "N", "T", "W"]
exclude = [
    "venv",
    "env",
    ".venv",
    ".env",
    "__init__.py",
]
select = ["C", "D", "E", "F", "I", "N", "T", "W"]
ignore = ["D100", "D101", "D103", "D203", "D205","D212", "D413"]

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
