"""Default settings generated by cloudisk."""

#########################
# 'general' settings
#########################

# The path where the static files will be served from.
STATIC_PATH = ...


#########################
# 'protected' settings
#########################

# The email of the account that sends the account verifying email
EMAIL_FROM = ...

# The password of the account that sends the account verifying email
PASS_FROM = ...
