name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install pytest
        run: uv sync --group test

      - name: Run coverage
        run: pytest --cov=. --cov-report=term-missing --cov-report=xml  # generates coverage.xml

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          format: cobertura
          file: coverage.xml
