name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]

    env:
      OS_NAME: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install tox
        run: uv sync --group test

      - name: Translate Python version to tox env
        id: translate
        shell: bash
        run: |
          ENVNAME="py${{ matrix.python-version }}"
          ENVNAME="${ENVNAME//./}"
          echo "envname=$ENVNAME" >> $GITHUB_OUTPUT

      - name: Run tests and generate coverage reports
        run: uv run tox -e ${{ steps.translate.outputs.envname }}

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          parallel: true
          file: reports/coverage-${{ matrix.os }}-${{ steps.translate.outputs.envname }}.xml

  upload:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
